autocode:
    web: web/src
    root: /Users/hanjingong/GolandProjects/GONG
    server: server
    module: github.com/richardgong1987/server
    ai-path: ""
aws-s3:
    bucket: ""
    region: ""
    endpoint: ""
    secret-id: ""
    secret-key: ""
    base-url: ""
    path-prefix: ""
    s3-force-path-style: false
    disable-ssl: false
# minio oss configuration
minio:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  use-ssl: false
  base-path: ""
  bucket-url: "http://host:9000/yourBucketName"
captcha:
    key-long: 6
    img-width: 240
    img-height: 80
    open-captcha: 0
    open-captcha-timeout: 3600
cloudflare-r2:
    bucket: ""
    base-url: ""
    path: ""
    account-id: ""
    access-key-id: ""
    secret-access-key: ""
cors:
    mode: strict-whitelist
    whitelist:
        - allow-origin: example1.com
          allow-methods: POST, GET
          allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
        - allow-origin: example2.com
          allow-methods: GET, POST
          allow-headers: content-type
          expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
          allow-credentials: true
db-list:
    - type: ""
      alias-name: ""
      prefix: ""
      port: ""
      config: ""
      db-name: ""
      username: ""
      password: ""
      path: ""
      engine: ""
      log-mode: ""
      max-idle-conns: 10
      max-open-conns: 100
      singular: false
      log-zap: false
      disable: true
disk-list:
    - mount-point: /
email:
    to: xxx@qq.com
    from: xxx@163.com
    host: smtp.163.com
    secret: xxx
    nickname: test
    port: 465
    is-ssl: true
excel:
    dir: ./resource/excel/
jwt:
    signing-key: 88a6daa6-5039-4e33-876b-205386eea2ff
    expires-time: 7d
    buffer-time: 1d
    issuer: qmPlus
local:
    path: uploads/file
    store-path: uploads/file
mysql:
    prefix: ""
    port: "3306"
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: gong
    username: root
    password: password
    path: 127.0.0.1
    engine: ""
    log-mode: error
    max-idle-conns: 10
    max-open-conns: 100
    singular: false
    log-zap: false
oracle:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 0
    max-open-conns: 0
    singular: false
    log-zap: false
pgsql:
    prefix: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    path: ""
    engine: ""
    log-mode: ""
    max-idle-conns: 0
    max-open-conns: 0
    singular: false
    log-zap: false
redis:
    name: ""
    addr: 127.0.0.1:6379
    password: ""
    db: 0
    useCluster: false
    clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
redis-list:
    - name: cache
      addr: 127.0.0.1:6379
      password: ""
      db: 0
      useCluster: false
      clusterAddrs:
        - 172.21.0.3:7000
        - 172.21.0.4:7001
        - 172.21.0.2:7002
system:
    db-type: mysql
    oss-type: local
    router-prefix: ""
    addr: 8888
    iplimit-count: 15000
    iplimit-time: 3600
    use-multipoint: false
    use-redis: false
    use-mongo: false
    use-strict-auth: false
zap:
    level: info
    prefix: '[github.com/richardgong1987/server]'
    format: console
    director: log
    encode-level: LowercaseColorLevelEncoder
    stacktrace-key: stacktrace
    show-line: true
    log-in-console: true
    retention-day: -1
